const HOST = 'com.deepcreator.browser'
const shared = new Set()
const controlled = new Map()
const revisions = new Map()
const navigationRevisions = new Map()
const snapshots = new Map()
const attached = new Set()
const pausedRequests = new Map()
const dialogs = new Map()
const AGENT_GROUP_TITLE = 'DeepCreator Agent'
let port

function actionSteps(command) { const steps=command.steps||(command.action?[{action:command.action,locator:command.locator,destination:command.destination,value:command.value,files:command.files}]:[]);if(!steps.length)throw Object.assign(new Error('browser_act requires one action or steps.'),{code:'BROWSER_UNAVAILABLE'});return steps }
function matchesUrl(url,pattern,mode) { const resolved=mode||(pattern.includes('*')?'glob':'contains');if(resolved==='exact')return url===pattern;if(resolved==='contains')return url.includes(pattern);const escaped=pattern.replace(/[|\\{}()[\]^$+?.]/g,'\\$&').replace(/\*\*/g,'\u0000').replace(/\*/g,'[^/]*').replace(/\u0000/g,'.*');return new RegExp(`^${escaped}$`).test(url) }

function connect() {
  port = chrome.runtime.connectNative(HOST)
  port.onMessage.addListener(message => { if(message?.kind==='network-decision'){const paused=pausedRequests.get(message.decisionId);if(paused){pausedRequests.delete(message.decisionId);clearTimeout(paused.timer);void cdp(paused.tabId,message.allow?'Fetch.continueRequest':'Fetch.failRequest',message.allow?{requestId:paused.requestId}:{requestId:paused.requestId,errorReason:'BlockedByClient'})}return}void dispatch(message) })
  port.onDisconnect.addListener(() => { port = undefined; setTimeout(connect, 2000) })
}
function send(value) { try { port?.postMessage(value) } catch {} }
function fail(id, error) { send({ id, ok: false, error: { code: error?.code || 'BROWSER_UNAVAILABLE', message: error?.message || String(error), ...(error?.details ? { details: error.details } : {}) } }) }
function state(tab) { return { providerTabId: String(tab.id), url: tab.url || '', title: tab.title || '', loading: tab.status === 'loading', canGoBack: false, canGoForward: false, presentation: { owner: 'provider', mode: 'live', requiredBeforeControl: false } } }
async function tabOf(providerTabId) { const tab = await chrome.tabs.get(Number(providerTabId)); if (!tab.id) throw new Error('Chrome tab is gone.'); return tab }
async function attach(tabId) { if(attached.has(tabId))return;try { await chrome.debugger.attach({ tabId }, '1.3') } catch (error) { if (!String(error).includes('already attached')) throw error }await chrome.debugger.sendCommand({tabId},'Fetch.enable',{patterns:[{urlPattern:'http://*/*'},{urlPattern:'https://*/*'}]});attached.add(tabId) }
async function cdp(tabId, method, params = {}) { await attach(tabId); return chrome.debugger.sendCommand({ tabId }, method, params) }
chrome.debugger.onDetach.addListener(source=>attached.delete(source.tabId))
chrome.debugger.onEvent.addListener((source,method,params)=>{if(method==='Page.javascriptDialogOpening'){dialogs.set(source.tabId,params);return}if(method!=='Fetch.requestPaused'||!controlled.has(source.tabId))return;const decisionId=crypto.randomUUID();const timer=setTimeout(()=>{const paused=pausedRequests.get(decisionId);if(!paused)return;pausedRequests.delete(decisionId);void cdp(source.tabId,'Fetch.failRequest',{requestId:params.requestId,errorReason:'TimedOut'})},5000);pausedRequests.set(decisionId,{tabId:source.tabId,requestId:params.requestId,timer});send({event:'network-request',providerTabId:String(source.tabId),decisionId,url:params.request.url})})
async function installInputGuard(tabId) {
  await chrome.scripting.executeScript({ target: { tabId, allFrames: true }, func: () => {
    if (globalThis.__deepcreatorInputGuard) return; globalThis.__deepcreatorInputGuard = true
    for (const event of ['pointerdown', 'keydown', 'beforeinput']) addEventListener(event, value => { if (value.isTrusted) chrome.runtime.sendMessage({ type: 'deepcreator-user-input' }) }, true)
  } }).catch(() => undefined)
}
chrome.runtime.onMessage.addListener((message, sender) => { if (message?.type === 'deepcreator-user-input' && sender.tab?.id && controlled.has(sender.tab.id)) send({ event: 'control-interrupted', providerTabId: String(sender.tab.id) }) })
chrome.action.onClicked.addListener(tab => { if (!tab.id) return; if (shared.has(tab.id)) shared.delete(tab.id); else shared.add(tab.id); revisions.set(tab.id, (revisions.get(tab.id) || 0) + 1); void chrome.action.setBadgeText({ tabId: tab.id, text: shared.has(tab.id) ? 'ON' : '' }) })
chrome.tabs.onUpdated.addListener((tabId,changeInfo) => { if (shared.has(tabId) || controlled.has(tabId)) { revisions.set(tabId, (revisions.get(tabId) || 0) + 1);if(changeInfo.url!==undefined||changeInfo.status==='loading')navigationRevisions.set(tabId,(navigationRevisions.get(tabId)||0)+1);send({ event: 'state-changed', providerTabId: String(tabId) }) } })
chrome.tabs.onRemoved.addListener(tabId => { shared.delete(tabId); controlled.delete(tabId); revisions.delete(tabId); navigationRevisions.delete(tabId); snapshots.delete(String(tabId)); send({ event: 'state-changed', providerTabId: String(tabId) }) })

async function snapshot(tab) {
  const [{ result }] = await chrome.scripting.executeScript({ target: { tabId: tab.id }, func: () => {
    const visible = element => { const box = element.getBoundingClientRect(); const style = getComputedStyle(element); return box.width > 0 && box.height > 0 && style.visibility !== 'hidden' && style.display !== 'none' }
    const selector = element => { if (element.id) return `#${CSS.escape(element.id)}`; const parts=[]; for(let node=element; node&&node.nodeType===1&&parts.length<6;node=node.parentElement){let part=node.tagName.toLowerCase();const siblings=node.parentElement?[...node.parentElement.children].filter(x=>x.tagName===node.tagName):[];if(siblings.length>1)part+=`:nth-of-type(${siblings.indexOf(node)+1})`;parts.unshift(part)} return parts.join('>') }
    const editable=new Set(['text','search','email','tel','url','number','range','color','date','time','datetime-local','month','week'])
    const role=element=>{const explicit=element.getAttribute('role');if(explicit)return explicit;const tag=element.tagName.toLowerCase();if(tag==='a'&&element.hasAttribute('href'))return'link';if(tag==='button')return'button';if(tag==='textarea')return'textbox';if(tag==='select')return element.multiple||element.size>1?'listbox':'combobox';if(tag!=='input')return tag;const type=String(element.type||'text').toLowerCase();if(['button','submit','reset','image'].includes(type))return'button';if(type==='checkbox')return'checkbox';if(type==='radio')return'radio';if(type==='range')return'slider';if(type==='number')return'spinbutton';if(type==='search')return'searchbox';return'textbox'}
    const name=element=>{const labelledBy=String(element.getAttribute('aria-labelledby')||'').split(/\s+/).filter(Boolean).map(id=>document.getElementById(id)?.innerText||document.getElementById(id)?.textContent||'').join(' ').trim();return String(element.getAttribute('aria-label')||labelledBy||element.labels?.[0]?.innerText||element.labels?.[0]?.textContent||element.getAttribute('alt')||element.getAttribute('title')||element.innerText||element.textContent||element.placeholder||'').trim().slice(0,240)}
    const rows=[...document.querySelectorAll('a,button,input,textarea,select,[role],[tabindex]')].filter(visible).slice(0,500).map(element => { const inputType=element.type||undefined,autocomplete=element.autocomplete||undefined,identity=[element.id,element.getAttribute('name'),inputType,autocomplete].filter(Boolean).join(' '),sensitive=inputType==='password'||autocomplete==='one-time-code'||String(autocomplete||'').startsWith('cc-')||/(?:token|secret|signature|authorization|authenticity|csrf|xsrf|session|credential|otp|passcode|api[-_]?key)/i.test(identity),exposesValue=element instanceof HTMLTextAreaElement||element instanceof HTMLSelectElement||(element instanceof HTMLInputElement&&editable.has(element.type)),semanticRole=role(element),accessibleName=name(element),href=element instanceof HTMLAnchorElement?element.href:undefined,target=element instanceof HTMLAnchorElement?element.target||undefined:undefined,form=(element instanceof HTMLInputElement||element instanceof HTMLButtonElement)?element.form:undefined;return { selector: selector(element), role: semanticRole, name: accessibleName, ...(!sensitive&&exposesValue?{value:String(element.value||'').slice(0,240)}:{}), ...(inputType?{inputType}:{}), ...(autocomplete?{autocomplete}:{}), ...(href?{href}:{}), ...(target?{target,opensNewTab:target==='_blank'}:{}), ...(form?.action?{formAction:form.action}:{}), ...(form?.method?{formMethod:form.method.toUpperCase()}:{}) } });const counts=new Map;for(const row of rows){if(!row.name)continue;const key=row.role+'\n'+row.name;counts.set(key,(counts.get(key)||0)+1)}return rows.map(row=>({...row,stableLocators:row.name&&counts.get(row.role+'\n'+row.name)===1?[{kind:'role',role:row.role,name:row.name,exact:true}]:[]}))
  } })
  const snapshotId = `snapshot-${crypto.randomUUID()}`; const selectors = new Map(); const nodes = (result || []).map((row, index) => { const nodeRef=`n${index+1}`; selectors.set(nodeRef,row.selector); const {selector:_selector,...node}=row;return {nodeRef,...node} }); snapshots.set(String(tab.id), { snapshotId, selectors }); return { snapshotId, url: tab.url || '', title: tab.title || '', text: nodes.map(n=>`${n.nodeRef} ${n.role} ${JSON.stringify(n.name)}${n.stableLocators?.[0]?` stable=${JSON.stringify(n.stableLocators[0])}`:''}`).join('\n'), nodes }
}
async function documentPage(tab, command) {
  const [{ result }] = await chrome.scripting.executeScript({ target: { tabId: tab.id }, args: [{ documentId: command.documentId, offset: command.offset, maxChars: command.maxChars }], func: input => {
    const SOURCE_LIMIT=2*1024*1024,DEFAULT_PAGE=12000,MAX_PAGE=20000,contentType=String(document.contentType||'text/html').toLowerCase(),raw=/^(?:text\/plain|application\/(?:json|xml)|text\/xml)/.test(contentType)||/raw\.githubusercontent\.com$/i.test(location.hostname)
    const hidden=el=>{for(let node=el;node&&node!==document.documentElement;node=node.parentElement){if(node.matches('script,style,noscript,template,svg,[hidden],[inert],[aria-hidden="true"]'))return true;const style=getComputedStyle(node);if(style.display==='none'||style.visibility==='hidden'||style.opacity==='0')return true}return false}
    const safeUrl=value=>{try{const url=new URL(value,location.href);if(!['http:','https:'].includes(url.protocol))return'';url.username='';url.password='';url.search='';url.hash='';return url.href}catch{return''}}
    const clean=value=>String(value||'').replace(/\u00a0/g,' ').replace(/[ \t]+\n/g,'\n').replace(/\n[ \t]+/g,'\n').replace(/[ \t]{2,}/g,' ').replace(/\n{3,}/g,'\n\n').trim()
    let sections=[]
    if(raw){const source=document.querySelector('pre')||document.body;sections=[clean(source?.textContent||'')]}else{const root=document.querySelector('main,article')||document.body;if(root){const nodes=[...root.querySelectorAll('h1,h2,h3,h4,h5,h6,p,blockquote,li,pre,tr,dt,dd')].filter(el=>!hidden(el)&&!(el.matches('li')&&el.querySelector(':scope > ul,:scope > ol')));for(const el of nodes){let value=el.matches('tr')?[...el.querySelectorAll(':scope > th,:scope > td')].map(cell=>clean(cell.innerText||cell.textContent||'')).filter(Boolean).join(' | '):clean(el.innerText||el.textContent||'');if(!value)continue;const links=el.matches('a[href]')?[el]:[...el.querySelectorAll('a[href]')],destinations=[...new Set(links.map(link=>safeUrl(link.getAttribute('href')||'')).filter(Boolean))];sections.push(value+(destinations.length?'\nLinks: '+destinations.join(' '):''))}}}
    let text=clean([document.title?('# '+clean(document.title)):'',...sections].filter(Boolean).join('\n\n')),sourceTruncated=text.length>SOURCE_LIMIT;if(sourceTruncated)text=text.slice(0,SOURCE_LIMIT);let hash=2166136261,identity=location.href+'\n'+contentType+'\n'+text;for(let i=0;i<identity.length;i++){hash^=identity.charCodeAt(i);hash=Math.imul(hash,16777619)}const documentId='document-'+(hash>>>0).toString(16)+'-'+text.length;if(input.documentId&&input.documentId!==documentId)return{error:'STALE_DOCUMENT',documentId,contentType};const offset=Math.max(0,Math.min(Number.isFinite(input.offset)?Math.trunc(input.offset):0,text.length)),maxChars=Math.max(1,Math.min(Number.isFinite(input.maxChars)?Math.trunc(input.maxChars):DEFAULT_PAGE,MAX_PAGE)),end=Math.min(text.length,offset+maxChars);return{documentId,text:text.slice(offset,end),offset,...(end<text.length?{nextOffset:end}:{}),truncated:end<text.length,contentType,...(sourceTruncated?{sourceTruncated:true}:{})}
  } })
  if(result?.error==='STALE_DOCUMENT')throw Object.assign(new Error('The page changed while continuing this document. Start again without documentId.'),{code:'STALE_DOCUMENT'})
  return result
}
function selectorFor(providerTabId, locator) { if (!locator) return undefined; if(locator.kind==='node'){const snap=snapshots.get(providerTabId);if(!snap||snap.snapshotId!==locator.snapshotId)throw Object.assign(new Error('Snapshot is stale.'),{code:'STALE_SNAPSHOT'});return snap.selectors.get(locator.nodeRef)} if(locator.kind==='text')return `text=${locator.text}`; return undefined }
async function act(tab, command) {
  const selector = selectorFor(String(tab.id), command.locator)
  const [{ result }] = await chrome.scripting.executeScript({ target: { tabId: tab.id }, args: [selector, command], func: (selector, command) => {
    let element
    const role=x=>{const explicit=x.getAttribute('role');if(explicit)return explicit;const tag=x.tagName.toLowerCase();if(tag==='a'&&x.hasAttribute('href'))return'link';if(tag==='button')return'button';if(tag==='textarea')return'textbox';if(tag==='select')return x.multiple||x.size>1?'listbox':'combobox';if(tag!=='input')return tag;const type=String(x.type||'text').toLowerCase();if(['button','submit','reset','image'].includes(type))return'button';if(type==='checkbox')return'checkbox';if(type==='radio')return'radio';if(type==='range')return'slider';if(type==='number')return'spinbutton';if(type==='search')return'searchbox';return'textbox'}
    const name=x=>String(x.getAttribute('aria-label')||x.labels?.[0]?.innerText||x.getAttribute('title')||x.innerText||x.placeholder||'').trim()
    let matches=[]
    if (command.locator?.kind === 'role') matches=[...document.querySelectorAll('a,button,input,textarea,select,[role],[tabindex]')].filter(x=>role(x)===command.locator.role&&(!command.locator.name||(command.locator.exact?name(x)===command.locator.name:name(x).includes(command.locator.name))))
    else if(command.locator?.kind==='label'){matches=[...document.querySelectorAll('label')].filter(x=>(x.innerText||'').includes(command.locator.label)).map(label=>label.control).filter(Boolean)}
    else if(selector?.startsWith('text=')){const text=selector.slice(5);matches=[...document.querySelectorAll('a,button,input,textarea,select,[role],[tabindex]')].filter(x=>command.locator?.exact?name(x)===text:(x.innerText||x.value||'').includes(text))}
    else element=selector?document.querySelector(selector):document.scrollingElement
    if(matches.length>1)throw new Error(`AMBIGUOUS_LOCATOR:${matches.length}`);if(matches.length===1)element=matches[0]
    if(!element)throw new Error('Element not found')
    let popupUrl;const originalOpen=globalThis.open;if(command.action==='click'||command.action==='press')globalThis.open=(url)=>{try{popupUrl=new URL(String(url||''),location.href).href}catch{};return null}
    try{if(command.action==='click'){if(element instanceof HTMLAnchorElement&&element.target==='_blank'){if(command.popupPolicy==='deny')popupUrl=element.href;else element.removeAttribute('target')}if(!(popupUrl&&command.popupPolicy==='deny'))element.click()}else if(command.action==='fill'||command.action==='type'){element.focus();element.value=command.action==='type'?String(element.value||'')+(command.value||''):command.value||'';element.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText'}));if(command.action==='fill')element.dispatchEvent(new Event('change',{bubbles:true}))}else if(command.action==='press'){const key=command.value||'Enter';element.dispatchEvent(new KeyboardEvent('keydown',{key,bubbles:true}));if(key==='Enter'){if(element.tagName==='BUTTON'||element.tagName==='A'){if(element instanceof HTMLAnchorElement&&element.target==='_blank'){if(command.popupPolicy==='deny')popupUrl=element.href;else element.removeAttribute('target')}if(!(popupUrl&&command.popupPolicy==='deny'))element.click()}else if(element.form){if(element.form.target==='_blank'){if(command.popupPolicy==='deny')popupUrl=element.form.action;else element.form.removeAttribute('target')}if(!(popupUrl&&command.popupPolicy==='deny'))element.form.requestSubmit()}}element.dispatchEvent(new KeyboardEvent('keyup',{key,bubbles:true}))}else if(command.action==='check'){element.checked=true;element.dispatchEvent(new Event('change',{bubbles:true}))}else if(command.action==='select'){element.value=command.value||'';element.dispatchEvent(new Event('change',{bubbles:true}))}else if(command.action==='scroll')element.scrollBy?.(0,Number(command.value)||600)}finally{globalThis.open=originalOpen}
    const box=element.getBoundingClientRect(),style=getComputedStyle(element)
    const href=element instanceof HTMLAnchorElement?element.href:undefined,target=element instanceof HTMLAnchorElement?element.target||undefined:undefined,form=(element instanceof HTMLInputElement||element instanceof HTMLButtonElement)?element.form:undefined
    return { role: role(element), name: name(element), inputType: element.type, autocomplete: element.autocomplete, visible:box.width>0&&box.height>0&&style.visibility!=='hidden'&&style.display!=='none',...(href?{href}:{}),...(target?{target,opensNewTab:target==='_blank'}:{}),...(form?.action?{formAction:form.action}:{}),...(form?.method?{formMethod:form.method.toUpperCase()}:{}),...(popupUrl?{popupUrl}:{}) }
  } })
  return result
}
async function execute(providerTabId, command) {
  let tab=await tabOf(providerTabId); controlled.set(tab.id, true); await installInputGuard(tab.id)
  if(command.kind==='navigate'){if(command.action==='goto')await chrome.tabs.update(tab.id,{url:command.url});else if(command.action==='back')await chrome.tabs.goBack(tab.id);else if(command.action==='forward')await chrome.tabs.goForward(tab.id);else await chrome.tabs.reload(tab.id);tab=await tabOf(providerTabId);return{kind:'state',tab:state(tab)}}
  if(command.kind==='inspect'){if(command.action==='snapshot')return{kind:'snapshot',snapshot:await snapshot(tab),tab:state(await tabOf(providerTabId))};if(command.action==='screenshot'){const shot=await cdp(tab.id,'Page.captureScreenshot',{format:'png'});return{kind:'screenshot',dataUrl:`data:image/png;base64,${shot.data}`,tab:state(tab)}};if(command.action==='document')return{kind:'document',document:await documentPage(tab,command),tab:state(await tabOf(providerTabId))};if(command.action==='elementInfo'){const info=await act(tab,{...command,action:'inspect'}),{visible:_visible,...element}=info;return{kind:'elementInfo',element:{nodeRef:'element',...element},tab:state(tab)}}return{kind:'state',tab:state(tab)}}
  if(command.kind==='wait'){const deadline=Date.now()+(command.timeoutMs||15000);let matched=false;while(Date.now()<deadline){tab=await tabOf(providerTabId);if(command.condition==='load'&&tab.status==='complete')matched=true;else if(command.condition==='url'&&matchesUrl(tab.url||'',command.value||'',command.urlMatch))matched=true;else if(command.condition==='dialog'&&dialogs.has(tab.id)){matched=true;dialogs.delete(tab.id);await cdp(tab.id,'Page.handleJavaScriptDialog',{accept:false})}else if(command.condition==='visible'||command.condition==='hidden'){try{const info=await act(tab,{locator:command.locator,action:'inspect'});matched=command.condition==='visible'?info.visible:!info.visible}catch(error){if(String(error?.message||error).includes('Element not found'))matched=command.condition==='hidden';else throw error}}if(matched)break;await new Promise(r=>setTimeout(r,100))}if(!matched)throw Object.assign(new Error(`Chrome wait timed out: ${command.condition}`),{code:'TIMEOUT',details:{finalUrl:tab.url}});return{kind:'state',tab:state(tab)}}
  const steps=actionSteps(command),navigationRevision=navigationRevisions.get(tab.id)||0,popupPolicy=command.popupPolicy||(command.expected==='navigation'?'same-tab':'deny')
  for(const [index,step] of steps.entries()){try{if(step.action==='upload'){const selector=selectorFor(providerTabId,step.locator);if(!selector||selector.startsWith('text='))throw Object.assign(new Error('Chrome upload requires a fresh snapshot node locator.'),{code:'STALE_SNAPSHOT'});const expression=`document.querySelector(${JSON.stringify(selector)})`,evaluated=await cdp(tab.id,'Runtime.evaluate',{expression,returnByValue:false});if(!evaluated.result?.objectId)throw Object.assign(new Error('Upload input is no longer present.'),{code:'STALE_SNAPSHOT'});await cdp(tab.id,'DOM.setFileInputFiles',{objectId:evaluated.result.objectId,files:step.files||[]})}else{const actionResult=await act(tab,{...step,popupPolicy});if(actionResult?.popupUrl){if(popupPolicy==='deny')throw Object.assign(new Error('The action requested a new page, but popupPolicy=deny. No navigation wait was performed.'),{code:'POPUP_BLOCKED',details:{popupUrl:actionResult.popupUrl,completedSteps:index+1,actionApplied:true,failedPhase:'postcondition',postcondition:'navigation',finalTab:state(await tabOf(providerTabId))}});await chrome.tabs.update(tab.id,{url:actionResult.popupUrl})}}}catch(error){const message=String(error?.message||error),ambiguous=/AMBIGUOUS_LOCATOR:(\d+)/.exec(message);if(ambiguous){error.code='AMBIGUOUS_LOCATOR';error.message=`Locator matched ${ambiguous[1]} elements. Use a unique snapshot nodeRef or a more specific exact locator.`}error.details={...(error.details||{}),failedStep:index,completedSteps:error.details?.completedSteps??index,actionApplied:error.details?.actionApplied??index>0,failedPhase:error.details?.failedPhase||'action',finalTab:error.details?.finalTab||state(await tabOf(providerTabId))};throw error}}
  if(command.expected==='navigation'){const started=Date.now(),deadline=started+30000;while(Date.now()<deadline){tab=await tabOf(providerTabId);if((navigationRevisions.get(tab.id)||0)!==navigationRevision&&tab.status==='complete')break;await new Promise(r=>setTimeout(r,50))}if((navigationRevisions.get(tab.id)||0)===navigationRevision)throw Object.assign(new Error(`Action completed (${steps.length}/${steps.length} steps), but the navigation postcondition did not occur. The mutation was applied and the previous snapshot is invalid.`),{code:'POSTCONDITION_TIMEOUT',details:{finalUrl:tab.url,finalTab:state(tab),completedSteps:steps.length,actionApplied:true,failedPhase:'postcondition',postcondition:'navigation',durationMs:Date.now()-started,suggestedNextStep:'Inspect Browser events and the current URL; do not retry the mutation or add a fixed sleep.'}})}
  if(command.expectedUrl){const started=Date.now(),deadline=started+30000;while(Date.now()<deadline){tab=await tabOf(providerTabId);if(matchesUrl(tab.url||'',command.expectedUrl,command.urlMatch))break;await new Promise(r=>setTimeout(r,50))}if(!matchesUrl(tab.url||'',command.expectedUrl,command.urlMatch))throw Object.assign(new Error(`Action completed (${steps.length}/${steps.length} steps), but the URL postcondition was not satisfied. The mutation was applied and the previous snapshot is invalid.`),{code:'POSTCONDITION_TIMEOUT',details:{finalUrl:tab.url,finalTab:state(tab),completedSteps:steps.length,actionApplied:true,failedPhase:'postcondition',postcondition:'url',durationMs:Date.now()-started}})}
  return{kind:'state',tab:state(await tabOf(providerTabId))}
}
async function dispatch(request) { const {id,method,params={}}=request; try { let result
  if(method==='createTab'){let tab=await chrome.tabs.create({url:'about:blank',active:true});const groupId=await chrome.tabs.group({tabIds:[tab.id]});await chrome.tabGroups.update(groupId,{title:AGENT_GROUP_TITLE,color:'blue',collapsed:false});controlled.set(tab.id,params.automationSessionId);await attach(tab.id);await installInputGuard(tab.id);if(params.request?.url){await chrome.tabs.update(tab.id,{url:params.request.url});tab=await chrome.tabs.get(tab.id)}result=state(tab)}
  else if(method==='listAgentTabs'){result=[];for(const tabId of controlled.keys())try{result.push(state(await chrome.tabs.get(tabId)))}catch{}}
  else if(method==='listUserTabs'){result=[];for(const tabId of shared)try{const tab=await chrome.tabs.get(tabId);result.push({...state(tab),revision:revisions.get(tabId)||0})}catch{}}
  else if(method==='claimUserTab'){const tab=await chrome.tabs.get(Number(params.candidate.providerTabId));const current={...state(tab),revision:revisions.get(tab.id)||0};if(current.url!==params.candidate.url||current.title!==params.candidate.title||current.revision!==params.candidate.revision)throw Object.assign(new Error('Shared tab changed; list it again.'),{code:'STALE_SNAPSHOT'});controlled.set(tab.id,params.automationSessionId);await attach(tab.id);await installInputGuard(tab.id);result=state(tab)}
  else if(method==='execute')result=await execute(params.providerTabId,params.command)
  else if(method==='show'||method==='resumeControl'){const tab=await tabOf(params.providerTabId);await chrome.windows.update(tab.windowId,{focused:true});await chrome.tabs.update(tab.id,{active:true});controlled.set(tab.id,true);result=state(await tabOf(params.providerTabId))}
  else if(method==='release'){controlled.delete(Number(params.providerTabId));try{await chrome.debugger.detach({tabId:Number(params.providerTabId)})}catch{};result=null}
  else if(method==='close'){controlled.delete(Number(params.providerTabId));await chrome.tabs.remove(Number(params.providerTabId));result=null}
  else throw new Error(`Unknown method ${method}`);send({id,ok:true,result})
} catch(error){fail(id,error)} }
connect()
