/**
 * The app-stage agent-preset materializer.
 *
 * The `app-stage-agent` plugin row exists ONLY inside the preset composition
 * (tool availability is permission); it is never a bundle row. This module
 * materializes that preset under `$DSH_HOME/.agent-presets/app-stage/`:
 *
 * - `agent.cordis.yml` — the standard agent toolset (shell, files, search,
 *   skills, goals, plan mode, compaction, delegation, ask/todo/web) plus the
 *   `file:` URL row loading the built agent package and the app-stage persona
 *   (a session that cannot write files cannot develop apps).
 * - `skills/` — the preset-carried `app-dev` and `workstage-use` skills.
 * - `preset.yml` — display metadata.
 * - `.deepcreator-stamp.json` — generator version, agent entry, and digests
 *   of every generated file, so a tampered or drifted preset is detected on
 *   boot, warned about loudly, and re-materialized (the preset is generated
 *   property, not user data).
 * @module @ryanyujazz/dsh-app-stage/preset
 */
import { createHash } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { join, dirname } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { APP_STAGE_SKILLS } from './preset-skills.ts'

/** Preset id — also the directory name under `.agent-presets/`. */
export const APP_STAGE_PRESET_ID = 'app-stage'

/** Stamp file name (generated-property marker; not part of the preset contract). */
const STAMP_FILE = '.deepcreator-stamp.json'

interface PresetStamp {
  readonly generator: number
  readonly agentEntry: string
  readonly agentDigest: string
  readonly compositionDigest: string
  readonly skillsDigest: string
}

/** Bump when the generated files' shape changes (drifted stamps re-materialize). */
const GENERATOR_VERSION = 7

const digest = (bytes: Uint8Array): string => createHash('sha256').update(bytes).digest('hex')
const nodeRequire = createRequire(import.meta.url)

/**
 * Resolve the built agent-package entry as a `file:` URL (S5 form).
 * Resolution walks the package dependency edge, so the answer follows the
 * installation (repo checkout under link: deps, node_modules in a packaged
 * install) instead of hard-coding a path.
 */
export function agentEntryUrl(): string {
  return pathToFileURL(nodeRequire.resolve('@ryanyujazz/dsh-app-stage-agent')).href
}

const PERSONA = [
  '你是 App Stage 应用开发会话的驻场工程师，由 {{model}} 模型驱动，当前工作目录为 {{cwd}}。你在 DeepCreator 的应用舞台上工作：把想法变成能上架的小应用，也替用户驾驶已安装的应用。',
  '',
  '开发（写应用）：',
  '1. 每个应用是 `<工作区>/.deepcreator/apps/<appId>/` 下一个自包含目录：`app.json`（manifest v1）+ 入口 HTML + 静态资源；目录名必须等于 manifest id。',
  '2. 写完先 `app_list` 过闸：条目必须 status=ready 才能继续；incomplete/rejected 时读 reason.fix 修复源码，不要硬闯。',
  '3. 自测用 ready 条目的 originURL 开自己的浏览器实例走查（双视角：首次进入的空态 + 操作后的状态），不要让用户当小白鼠。',
  '4. 应用数据一律走数据桥（`data.get/set/subscribe`），绝不把状态埋进 localStorage；渲染保持纯展示。',
  '5. 上桌唯一路径是发布审批（`app_publish`：机器扫描与探针通过后，首发与异源更新需用户批准，同源小版本免确认）；普通会话写 apps 目录只进开发中菜单，永不上桌。',
  '',
  '使用（驾应用）：先 `app_list` 后 `app_manifest`（渐进披露），再按指南操作；操作对等——用户在界面能做的，你也应有对应通道。',
  '- 驱动走结构化命令通道 `app_invoke`（只寻址已安装版，参数按声明键名与类型校验；返回带 {appId, version} 供技能包版本感知），绝不 DOM 自动化代替声明 action。',
  '- 数据进出走 `app_data_read` / `app_data_write`（键路径级，写即广播到所有打开实例；AppData 是唯一事实源，DOM 只是投影——验证效果先读数据）。',
  '- 呈现走 `app_open`（focus:true 是你切用户视图的唯一合法触发点，仅在用户要求看或成品就绪时用；focus:false 只开容器亮活动信号）。你在对话模式驱动应用时，侧边栏「应用」亮活动点并出现活动 chip——用户看得见你在操作什么。',
  '- 超时纪律（E1）：`app_invoke` 超时的命令可能已执行——先 `app_data_read` 验证效果再决定重试，非幂等 action 禁盲目重发；同一应用连续 5 次失败会熔断（CIRCUIT_OPEN），先 `app_list`/`app_manifest` 诊断根因，不要硬闯。',
  '- 二进制产物（生成图/视频）永不进 AppData 与 invoke params：`app_asset_write` 把 workspace 文件送进应用自己的同源资产目录（被动媒体白名单+内容校验+配额，同名覆盖即回收），AppData 只存返回的 url 引用；放置前 `app_asset_list` 清点去重。',
  '',
  '纪律：错误显式可行动；改完源码立即重新过闸复测；文档与 AGENT.md 随应用走。',
].join('\n')

/**
 * The generated composition. Rows mirror the deployment's `standard` preset
 * (the tool rows are unchanged there — see the media-producer precedent);
 * what this preset adds is the persona, the skills directory, and the
 * app-stage-agent row carrying the `app_*` tool face.
 */
function compositionFor(agentUrl: string): string {
  return [
    '# Generated by @ryanyujazz/dsh-app-stage — do not edit; changes are re-materialized.',
    '# The standard agent toolset plus the app-stage additions: a session that',
    '# cannot write files cannot develop apps. The app-stage-agent row loads the',
    '# built plugin by absolute file: URL (S5: load-path equivalence with a',
    '# package-name row; both end at the same built lib).',
    '',
    '# ── identity ────────────────────────────────────────────────────────────────',
    '- id: persona',
    "  name: '@deepseek-ai/dsh-persona'",
    '  config:',
    `    text: |-`,
    ...PERSONA.split('\n').map(line => `      ${line}`),
    '',
    '- id: agent-instructions',
    "  name: '@deepseek-ai/dsh-agent-instructions'",
    '  config:',
    '    maxBytes: 65536',
    '',
    '# ── shell ───────────────────────────────────────────────────────────────────',
    '- id: tool-bash',
    "  name: '@deepseek-ai/dsh-tool-bash'",
    '  disabled: !!js process.platform === \'win32\'',
    '- id: tool-pwsh',
    "  name: '@deepseek-ai/dsh-tool-pwsh'",
    '  disabled: !!js process.platform !== \'win32\'',
    '',
    '# ── filesystem ──────────────────────────────────────────────────────────────',
    '- id: tool-fs',
    "  name: '@deepseek-ai/dsh-tool-fs'",
    '- id: tool-fs-search',
    "  name: '@deepseek-ai/dsh-tool-fs-search'",
    '  config:',
    '    sampleOverCapGlobResults: false',
    '',
    '# ── background jobs ────────────────────────────────────────────────────────',
    '- id: tool-jobs',
    "  name: '@deepseek-ai/dsh-tool-jobs'",
    '',
    '# ── skills (preset-carried: app-dev + workstage-use) ───────────────────────',
    '- id: skill-filesystem',
    "  name: '@deepseek-ai/dsh-skill-filesystem'",
    '  config:',
    "    customSkillDirs:",
    "      - !!js \"process.getBuiltinModule('node:url').fileURLToPath(new URL('skills/', baseUrl))\"",
    '- id: tool-skill',
    "  name: '@deepseek-ai/dsh-tool-skill'",
    '',
    '# ── goals / plan mode / compaction / delegation (standard) ──────────────────',
    '- id: tool-goal',
    "  name: '@deepseek-ai/dsh-tool-goal'",
    '',
    '- id: planning',
    '  name: cordis:group',
    '  group: true',
    '  isolate:',
    '    planMode: true',
    '  config:',
    '    - id: plan-mode',
    "      name: '@deepseek-ai/dsh-plan-mode'",
    '      config:',
    '        section: |',
    "          You are in plan mode. Stay in plan mode until exit_plan_mode succeeds or the user switches the session mode. Imperative language to implement changes means plan the implementation, not execute it. A user's conversational agreement — including an answer confirming something you asked — approves nothing and does not end plan mode; fold the confirmed decision into the plan and submit it through exit_plan_mode.",
    '',
    "          Explore first. Use non-mutating reads, searches, static analysis, and checks to ground the plan in the actual repository. Do not edit or write files, change configuration, run formatters or code generation that rewrites tracked files, commit, or otherwise carry out the plan. Prefer existing functions and patterns over new machinery.",
    '',
    "          The tool catalog stays the same across modes for request-cache stability. These plan-mode rules override any later tool description or guidance that suggests using mutation tools; those tools remain listed to keep the tool catalog unchanged. Do not use todo_write to track this planning phase: it tracks implementation after an approved plan, while the plan itself belongs to exit_plan_mode.",
    '',
    "          Resolve discoverable facts by inspection. Use ask_user_question only for user-owned choices or material ambiguity that inspection cannot answer. Do not ask the user where code lives or how current behavior works when you can find out.",
    '',
    "          Make the plan decision-complete: state the goal and success criteria; group implementation changes by subsystem; identify public API, schema, and data-flow changes; cover edge cases, failure modes, tests, acceptance criteria, and explicit assumptions. Keep it concise enough to review but detailed enough that another engineer can implement it without making design decisions.",
    '',
    '- id: compaction',
    '  name: cordis:group',
    '  group: true',
    '  isolate:',
    '    compaction: true',
    '    toolResultPruner: true',
    '  config:',
    '    - id: compaction-basic',
    "      name: '@deepseek-ai/dsh-compaction-basic'",
    '    - id: command-compact',
    "      name: '@deepseek-ai/dsh-command-compact'",
    '    - id: tool-result-pruner',
    "      name: '@deepseek-ai/dsh-compaction-tool-result-pruner'",
    '      config:',
    '        thresholdChars: 8192',
    '        headChars: 4096',
    '        tailChars: 1024',
    '',
    '- id: delegation',
    '  name: cordis:group',
    '  group: true',
    '  isolate:',
    '    workflowEngine: true',
    '  config:',
    '    - id: tool-subagent-control',
    "      name: '@deepseek-ai/dsh-tool-subagent-control'",
    '    - id: tool-subagent',
    "      name: '@deepseek-ai/dsh-tool-subagent'",
    '      config:',
    '        provider: spawn',
    '        toolName: subagent',
    '        backgroundMode: continuable',
    '    - id: workflow-worker-thread',
    "      name: '@deepseek-ai/dsh-workflow-worker-thread'",
    '      config:',
    '        provider: spawn',
    '    - id: tool-workflow',
    "      name: '@deepseek-ai/dsh-tool-workflow'",
    '',
    '# ── remaining model-facing rows ─────────────────────────────────────────────',
    '- id: tool-ask-user',
    "  name: '@deepseek-ai/dsh-tool-ask-user'",
    '- id: tool-todo',
    "  name: '@deepseek-ai/dsh-tool-todo'",
    '  config:',
    '    allowParallelInProgress: true',
    '- id: tool-web',
    "  name: '@deepseek-ai/dsh-tool-web'",
    '',
    '# ── user questions (the approval seam app_publish hangs on) ────────────────',
    '# No preset row here: the service is a HOST-plane row (composition line 36)',
    '# and preset sessions run inside that composition, so ctx.userQuestions is',
    '# already present (the media-producer precedent: its tool-ask-user also',
    "# injects 'userQuestions' with no preset row). A duplicate row would collide",
    '# on the service name.',
    '',
    '# ── the App Stage tool face (preset-only; never a bundle row) ───────────────',
    '- id: app-stage-agent',
    `  name: '${agentUrl}'`,
    '',
  ].join('\n')
}

function metadataFor(): string {
  return [
    'name: App Stage 开发会话',
    'description: 面向 App Stage 应用开发与驾驶的会话：携带 app_* 工具面（应用发现、清单读取、数据读写与发布链）与 app-dev/workstage-use 技能，仅在本预设会话内可用。',
    'order: 80',
    '',
  ].join('\n')
}

/**
 * Verify the materialized preset against the stamp; a missing, drifted, or
 * tampered preset is re-materialized and reported.
 * @param presetsRoot - Absolute `.agent-presets` directory.
 * @param log - Warning sink (tamper/drift reports).
 * @returns what happened, for boot diagnostics.
 */
export async function ensurePreset(presetsRoot: string, log: (message: string) => void): Promise<'materialized' | 'verified' | 'healed'> {
  const dir = join(presetsRoot, APP_STAGE_PRESET_ID)
  const compositionPath = join(dir, 'agent.cordis.yml')
  const metadataPath = join(dir, 'preset.yml')
  const stampPath = join(dir, STAMP_FILE)
  const skillsDir = join(dir, 'skills')

  const agentUrl = agentEntryUrl()
  const agentDigest = await digestFile(fileURLToPath(agentUrl))
  const composition = compositionFor(agentUrl)
  const stamp: PresetStamp = {
    generator: GENERATOR_VERSION,
    agentEntry: agentUrl,
    agentDigest,
    compositionDigest: digest(new TextEncoder().encode(composition)),
    skillsDigest: digestSkills(),
  }

  const existing = await readJson(stampPath) as Partial<PresetStamp> | undefined
  if (existing === undefined || existing.generator !== GENERATOR_VERSION || existing.agentEntry !== agentUrl || existing.agentDigest !== agentDigest || existing.skillsDigest !== stamp.skillsDigest) {
    if (existing !== undefined) log(`app-stage preset stamp mismatch (agent entry, generator, or skills drifted) — re-materializing ${dir}`)
    await materialize(dir, compositionPath, composition, metadataPath, metadataFor(), stampPath, stamp, skillsDir)
    return 'materialized'
  }
  const onDisk = await readFile(compositionPath, 'utf8').catch(() => undefined)
  if (onDisk === undefined || digest(new TextEncoder().encode(onDisk)) !== existing.compositionDigest) {
    log(`app-stage preset composition tampered or corrupted — re-materializing ${compositionPath}`)
    await materialize(dir, compositionPath, composition, metadataPath, metadataFor(), stampPath, stamp, skillsDir)
    return 'healed'
  }
  return 'verified'
}

async function materialize(dir: string, compositionPath: string, composition: string, metadataPath: string, metadata: string, stampPath: string, stamp: PresetStamp, skillsDir: string): Promise<void> {
  await mkdir(dir, { recursive: true })
  await writeFile(compositionPath, composition, 'utf8')
  await writeFile(metadataPath, metadata, 'utf8')
  await writeFile(stampPath, `${JSON.stringify(stamp, null, 2)}\n`, 'utf8')
  for (const [relative, body] of Object.entries(APP_STAGE_SKILLS)) {
    const file = join(skillsDir, relative)
    await mkdir(dirname(file), { recursive: true })
    await writeFile(file, body, 'utf8')
  }
}

/** Combined digest of every carried skill file (order-stable). */
function digestSkills(): string {
  const parts = Object.keys(APP_STAGE_SKILLS).sort().map(key => `${key}:${digest(new TextEncoder().encode(APP_STAGE_SKILLS[key]!))}`)
  return digest(new TextEncoder().encode(parts.join('\n')))
}

async function digestFile(path: string): Promise<string> {
  const bytes = await readFile(path).catch(() => new Uint8Array())
  return digest(bytes)
}

async function readJson(path: string): Promise<unknown> {
  try {
    return JSON.parse(await readFile(path, 'utf8')) as unknown
  } catch {
    return undefined
  }
}

/** Generated-preset paths (diagnostics and tests). */
export const presetDirectory = (presetsRoot: string): string => join(presetsRoot, APP_STAGE_PRESET_ID)
export const presetStampPath = (presetsRoot: string): string => join(presetDirectory(presetsRoot), STAMP_FILE)
export const presetCompositionPath = (presetsRoot: string): string => join(presetDirectory(presetsRoot), 'agent.cordis.yml')
